# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_tutorial"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_tutorial"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  +persist_docs:
    relation: true
    columns: true
  dbt_tutorial:
    staging:
      +materialized: view
      +schema: staging
    marts:
      core:
        +materialized: view
        +schema: core

dispatch:
  - macro_namespace: dbt
    search_order:
      - dbt_tutorial
      - dbt_snowflake_monitoring
      - dbt

query-comment:
  comment: "{{ dbt_snowflake_monitoring.get_query_comment(node) }}"
  append: true # Snowflake removes prefixed comments.
